#!/usr/bin/python3
import sys

def factorize(num):
    if num % 2 == 0:
        return num // 2, 2

    for i in range(3, int(num**0.5) + 1, 2):
        if num % i == 0:
            factor = num // i
            for j in range(3, int(factor**0.5) + 1, 2):
                if factor % j == 0 or i % j == 0:
                    break
            else:
                return factor, i

    return num, 1

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    filename = sys.argv[1]

    with open(filename, 'r') as file:
        for line in file:
            num = int(line.strip())
            factor1, factor2 = factorize(num)
            print(f"{num}={factor1}*{factor2}")

if __name__ == "__main__":
    main()
